---
title: "Midterm Project for Data Science in R"
author: "Quan Zhou"
date: "10/23/2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## County-level oil and gas production
```{r}
# load in the data via the Import Dataset feature in the workspace
df <- read.csv(file = "~/Documents/HW/MA615/MidtermProject/oilgascounty.csv")
set.seed(100)
# remove columns that are not useful
df <- df[,-c(1,2,5,6,7,8,33,34,35)]
# divide dataframe into two dataframes: one called df_oil and the other df_gas
df_oil <- df[c(1,2,3:14)]
df_gas <- df[c(1,2,15:26)]
# convert integer values to numeric
df_oil[, 3:14] <- sapply(df_oil[, 3:14], as.numeric)
df_gas[, 3:14] <- sapply(df_gas[, 3:14], as.numeric)

# split the dataframe by states and store them as a list
# list_oil_by_state <- split(df_oil, df_oil$Stabr)
# list_gas_by_state <- split(df_gas, df_gas$Stabr)

# use aggregate to compute the sum for each state
oilsum<-aggregate(df_oil[, 3:14], list(State=df_oil$Stabr), sum)
gassum<-aggregate(df_gas[, 3:14], list(State=df_gas$Stabr), sum)

# Go through each row and determine if any state produced nothing over 12 years
oilsum<-oilsum[apply(oilsum, 1, function(o) ! ( any(as.numeric(o[2:13])==0))),]
gassum<-gassum[apply(gassum, 1, function(g) ! ( any(as.numeric(g[2:13])==0))),]

# We are done clean and tidy the oil and gas data
saveRDS(oilsum, file="oil.rda")
saveRDS(gassum, file="gas.rda")
```

## Plotting oil production
```{r tidy=TRUE}
# output statistics of oil and gas production
summary(oilsum[2:13])
# Normal boxplot
boxplot(oilsum[2:13],
names = c("2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009","2010", "2011"),
main = "Oil Production in US (48 states)",
ylab = "# of barrels")
# since the top producing states, TX, ND, and AL have much larger values, we use log
log_oilsum <- log10(oilsum[2:13])
boxplot(log_oilsum[1:12],
names = c("2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009","2010", "2011"),
main = "Oil Production in US (48 states)",
ylab = "log10(# of barrels)")
# a better visualization for log plot using ggplot/plotly
library(ggplot2)
library(plotly)
#need reshape to further simply the two-way data
library("reshape2", lib.loc="/Library/Frameworks/R.framework/Versions/3.3/Resources/library")
oilsum2 <- melt(log_oilsum)
# convert year into vector

ggplot(oilsum2, aes(x = variable, y = value)) + geom_boxplot(aes(fill = variable)) + xlab("Year")+ylab("log10(# of barrels)") + ggtitle("Oil Production in US (48 states)")

```
## Plotting Gas production
```{r tidy=TRUE}
# output statistics of gas production
summary(gassum[2:13])
# plot using ggplot/plotly
gassum2 <- melt(log10(gassum[2:13]))
# convert year into vector
ggplot(gassum2, aes(x = variable, y = value)) + geom_boxplot(aes(fill = variable)) + xlab("Year") + ylab("log10(thousand cubic feet)") + ggtitle("Oil Production in US (48 states)")

```
